apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ include "general-environment.fullname" . }}
  annotations:
    templateName: {{ .Template.Name }}
    templateBasePath: {{ .Template.BasePath }}
spec:
  generators:
  - git:
      repoURL: 'ssh://git@github.com:Tiriyon/AoA.git'
      revision: main
      files:
      - path: "{{ .Values.global.path }}/configs/*.yaml"
  template:
    metadata:
      name: '{{`{{ path[1] }}-{{ path[2] }}-{{ argocd.appName }}`}}'
    spec:
      destination:
        name: '{{`{{ path[2] }}`}}'
        namespace: '{{`{{ path[1] }}`}}'
      project: default
      source:
        helm:
          values: '{{`{{ source.helm.values }}`}}'
        path: '{{`{{ source.path }}`}}'
        repoURL: 'ssh://git@github.com:Tiriyon/appmanifests.git'
        targetRevision: main
        {{/*
        targetRevision: '{{`{{ path[1] }}`}}'
        */}}
      syncPolicy:
        automated: {
          prune: true
        }
        syncOptions:
          - CreateNamespace=true
