apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: environments
  namespace: argocd
spec:
  generators:
  - git:
      directories:
      - path: applicationsets/*/*/*
      repoURL: 'ENVIRONMENTS REPO URL'
      revision: main
  template:
    metadata:
      name: env-{{ path[1] }}-{{ path[2] }}-{{ path.basename }}
    spec:
      destination:
        name: in-cluster
        namespace: argocd
      project: default
      source:
        helm:
          values: |
            global:
              path: '{{ path }}'
        path: '{{ path }}'
        repoURL: 'eENVIRONMENTS REPO'
        targetRevision: main
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
